aragon/buidler-aragon

package.json, src/tasks/start/utils/frontend/webserver.ts
Part of buidler plugin codebase review.
Follow @macor161 to not use a self-written webserver in favor of an existing library.
=> Use an existing package as static webserver

src/tasks/start/start-task.ts, test/tasks/start/start-task.test.ts
Fix https://github.com/aragon/aragon-cli/issues/1420
=> Uses flags instead of boolean params

src/tasks/start/utils/backend/backend.ts, src/tasks/start/utils/backend/proxy.ts, test/projects/counter/contracts/test/CounterV1.sol, test/tasks/start/utils/backend/proxy.test.ts
Part of fixing https://github.com/aragon/aragon-cli/issues/1431
=> Adds more tests for proxy.ts

src/tasks/start/utils/backend/backend.ts, src/tasks/start/utils/backend/repo.ts, test/tasks/start/utils/backend/repo.test.ts, test/tasks/start/utils/frontend/app.test.ts, test/tasks/start/utils/frontend/frontend.test.ts, test/test-helpers/assertRevert.ts
Fix https://github.com/aragon/aragon-cli/issues/1431
=> Add tests for repo.ts

package-lock.json, package.json, src/index.ts, src/params.ts, src/tasks/start-task.ts, src/tasks/start/backend/create-app.ts, src/tasks/start/backend/start-ganache.ts, src/tasks/start/backend/update-app.ts, src/tasks/start/frontend/aragon-client.ts, src/tasks/start/frontend/generate-artifacts.ts, src/tasks/start/start-backend.ts, src/tasks/start/start-frontend.ts, src/tasks/task-names.ts, src/types.ts, src/utils/onExit.ts, test/projects/counter/package.json, test/projects/token-wrapper/package.json, test/projects/token-wrapper/scripts/hooks.js, test/src/tasks/start/backend/counter-behavior.ts, test/src/tasks/start/backend/create-app.test.ts, test/src/tasks/start/backend/set-permissions.test.ts, test/src/tasks/start/backend/update-app.test.ts, test/src/utils/onExit.ts
Please see annotations in the "files changed" section for details on what was changed.
The PR contains a lot of minute little changes that were needed while porting all the official Aragon apps to the Buidler flow + some 1Hive apps.
=> Merge develop to master for release of 0.1.0

src/tasks/start/start-backend.ts, src/types.ts, src/ui/logger.ts, test/projects/test-app/aragon-hooks.js, test/projects/token-wrapper/scripts/hooks.js
The changes in this PR were implemented by @dapplion in #74 but features were split to create atomic PRs
=> Feature: Add hooks logger

package-lock.json, package.json, src/tasks/start/backend/bases/deploy-apm.ts, src/utils/appInstaller/index.ts, src/utils/appInstaller/utils.ts, src/utils/appName.ts, src/utils/generateArtifacts.ts, src/utils/namehash.ts
Use ethers namehash util and remove `eth-ens-namehash` dependency.
=> Refactor: Use ethers namehash util

src/config/aragon.ts, src/tasks/publish/index.ts, src/types.ts
Add `igonreFilesPath` as an extra config option that defaults to '.'
=> Refactor: Configure a ignoreFilesPath on the config options

package.json
=> v0.2.2: Add missing .tsconfig.json on production distribution

package.json
=> Remove duplicate `dist/src` from publish files

src/params.ts, src/utils/copyExternalArtifacts.ts
=> Fix: Add aragon/os path to external artifact paths

package.json, yarn.lock
=> Dependencies: Remove BigNumber as a peerDependency

.github/workflows/publish.yml, .github/workflows/test.yml
Aligns the workflow indentation to the Github documentation's style.
=> CI: fix yml indentation

package.json, src/config/networks.ts, test/projects/counter/package.json, test/projects/counter/yarn.lock, test/projects/test-app/package.json, test/projects/test-app/yarn.lock, test/projects/token-wrapper/package.json, test/projects/token-wrapper/yarn.lock, yarn.lock
When connecting to frame, the buidler plugin will identify itself as `BuidlerAragon`
Bumps buidler to v1.3.1
=> Add httpHeaders field to frame connections

package.json, src/tasks/start/backend/bases/deploy-apm.ts, src/tasks/start/backend/bases/deploy-bases.ts, src/tasks/start/backend/bases/deploy-ens.ts, src/tasks/start/backend/create-app.ts, src/tasks/start/backend/create-dao.ts, src/tasks/start/backend/set-permissions.ts, src/tasks/start/backend/update-app.ts, src/tasks/start/start-backend.ts, src/types.ts, src/utils/accounts.ts, src/utils/artifact/generateAragonArtifact.ts, test/projects/counter/package.json, test/projects/counter/yarn.lock, test/projects/test-app/package.json, test/projects/test-app/yarn.lock, test/projects/token-wrapper/package.json, test/projects/token-wrapper/yarn.lock, test/src/tasks/start/backend/bases/deploy-apm.test.ts, test/src/tasks/start/backend/bases/deploy-bases.test.ts, test/src/tasks/start/backend/bases/deploy-ens.test.ts, test/src/tasks/start/backend/create-app.test.ts, test/src/tasks/start/backend/create-dao.test.ts, test/src/tasks/start/backend/set-permissions.test.ts, test/src/tasks/start/backend/update-app.test.ts, yarn.lock
Use the `from` as default root account if configured on the `buidler.config`.
=> Chores before release

package.json
=> v0.2.6-rc.1

src/tasks/publish/index.ts, src/utils/artifact/findMissingManifestFiles.ts, src/utils/artifact/validateArtifacts.ts
Change publish task flag to skip artifact validation `skip-validation`
=> Change publish task flag

src/config/aragon.ts, src/tasks/start/backend/bases/deploy-bases.ts, src/types.ts
Add support for using custom base address during local development
=> Include aragon configuration for base addresses

src/config/networks.ts
=> Extract duplicate logic to a single function

src/utils/accounts.ts, test/projects/test-app/buidler.config.js, test/src/utils/accounts.test.ts
The `getRootAccount` logic had a wrong assignment when using the `from` account.
=> Fix root account
